## Bidirectional RNN for MIT-BIH dataset
We found that Bidirectional RNNs offer an improvement in performance over traditional RNNs (the improvement is much greater for the [PTBDB dataset](bilstm_ptbdb.ipynb)).

This model is a network with 2 bidirectional reccurent layers followed by a fully connected layer.

![Network](bilstm_mitbih.png)

In [1]:
import pandas as pd
import numpy as np

import tensorflow
from tensorflow.keras import optimizers, losses, activations, models
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, LearningRateScheduler, ReduceLROnPlateau
from tensorflow.keras.layers import Dense, Input, Dropout, GRU, \
    concatenate, Add, Activation
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import plot_model
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix

from IPython.display import Image

train = False

### Import data

In [2]:
df_train = pd.read_csv("../data/mitbih_train.csv", header=None)
df_train = df_train.sample(frac=1)
df_test = pd.read_csv("../data/mitbih_test.csv", header=None)

Y = np.array(df_train[187].values).astype(np.int8)
X = np.array(df_train[list(range(187))].values)[..., np.newaxis]

Y_test = np.array(df_test[187].values).astype(np.int8)
X_test = np.array(df_test[list(range(187))].values)[..., np.newaxis]

### Load model and skip to [evaluation](#evaluate)

In [3]:
model = load_model("bilstm_mitbih_model")

### Or ALTERNATIVELY train it by running:
python single_model_train_mitbih.py bilstm

### Evaluation
<a id='evaluate'></a>

In [6]:
pred_test = model.predict(X_test)
pred_test = np.argmax(pred_test, axis=-1)

f1 = f1_score(Y_test, pred_test, average="macro")

print("Test f1 score : %s "% f1)

acc = accuracy_score(Y_test, pred_test)

print("Test accuracy score : %s "% acc)

print(confusion_matrix(Y_test, pred_test))

Test f1 score : 0.8988133480926473 
Test accuracy score : 0.9810889822766308 
[[17996    69    37     3    13]
 [  149   394    10     2     1]
 [   47     5  1377    15     4]
 [   25     0    17   120     0]
 [   11     2     4     0  1591]]
