## RNN for MIT-BIH
This model is a network with 3 reccurent layers followed by 2 fully connected layers. We found the GRUs worked better than LSTMs, besides resulting in faster train times. We arrived at these parameters through [hyperparameter-tuning](hyperparameter-tuning_mitbih.py).

![Network](gru_mitbih.png)

In [1]:
import pandas as pd
import numpy as np

import tensorflow
from tensorflow.keras import optimizers, losses, activations, models
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, LearningRateScheduler, ReduceLROnPlateau
from tensorflow.keras.layers import Dense, Input, Dropout, GRU, \
    concatenate, Add, Activation
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import plot_model
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix

from IPython.display import Image

train = False

### Import data

In [2]:
df_train = pd.read_csv("../data/mitbih_train.csv", header=None)
df_train = df_train.sample(frac=1)
df_test = pd.read_csv("../data/mitbih_test.csv", header=None)

Y = np.array(df_train[187].values).astype(np.int8)
X = np.array(df_train[list(range(187))].values)[..., np.newaxis]

Y_test = np.array(df_test[187].values).astype(np.int8)
X_test = np.array(df_test[list(range(187))].values)[..., np.newaxis]

### Load model and skip to [evaluation](#evaluate)

In [3]:
model = load_model("gru_mitbih_model")

### Or ALTERNATIVELY train it by running
python single_model_train_mitbih.py gru

### Evaluation
<a id='evaluate'></a>

In [6]:
pred_test = model.predict(X_test)
pred_test = np.argmax(pred_test, axis=-1)

f1 = f1_score(Y_test, pred_test, average="macro")

print("Test f1 score : %s "% f1)

acc = accuracy_score(Y_test, pred_test)

print("Test accuracy score : %s "% acc)

print(confusion_matrix(Y_test, pred_test))

Test f1 score : 0.8817462021103077 
Test accuracy score : 0.9783482550703453 
[[17993    71    22     5    27]
 [  161   377    12     5     1]
 [   52     9  1347    23    17]
 [   28     1    15   118     0]
 [   18     4     3     0  1583]]
